name: fdroid_test
description: A new Flutter project for test Fdroid Build.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

